#drivers/input/touchscreen/focaltech_touch/focaltech_test
#
#Makefile for test module
#



obj-$(CONFIG_TOUCHSCREEN_FTS_MI) += focaltech_test.o focaltech_test_ini.o focaltech_test_detail_threshold.o
obj-$(CONFIG_TOUCHSCREEN_FTS_MI) += supported_ic/

